spring:
  application:
    name: json-dataset-api

  datasource:
    url: jdbc:mysql://localhost:3306/dataset_db
    username: root
    password: Yugen@1998
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.example: INFO
    org.springframework.web: INFO
